/* Generated by AN DISI Unibo */ 
package it.unibo.ctxCoapSimpleClient;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxCoapSimpleClient  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxcoapsimpleclient", "./srcMore/it/unibo/ctxCoapSimpleClient/coapsimpleclient.pl", 
		"./srcMore/it/unibo/ctxCoapSimpleClient/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	@SuppressWarnings("unused")
	QActorContext ctx = initTheContext();
} 	
}
