/* Generated by AN DISI Unibo */ 
package it.unibo.sender_actor;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractSender_actor extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractSender_actor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/sender_actor/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/sender_actor/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("sendPolarEvent",sendPolarEvent);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "sender_actor tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"sender_actor starts.\"";
	    	println( temporaryStr );  
	    	//switchTo sendPolarEvent
	        switchToPlanAsNextState(pr, myselfName, "sender_actor_"+myselfName, 
	              "sendPolarEvent",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun sendPolarEvent = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("sendPolarEvent",-1);
	    	String myselfName = "sendPolarEvent";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "p(Distance,Angle)","p(90,20)", guardVars ).toString();
	    	emit( "polar", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "sendPolarEvent";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "p(Distance,Angle)","p(40,120)", guardVars ).toString();
	    	emit( "polar", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "sendPolarEvent";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "p(Distance,Angle)","p(0,0)", guardVars ).toString();
	    	emit( "polar", temporaryStr );
	    	repeatPlanNoTransition(pr,myselfName,"sender_actor_"+myselfName,false,false);
	    }catch(Exception e_sendPolarEvent){  
	    	 println( getName() + " plan=sendPolarEvent WARNING:" + e_sendPolarEvent.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//sendPolarEvent
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
