/* Generated by AN DISI Unibo */ 
package it.unibo.ctxCoapSimpleClient;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Handlevalue extends AbstractHandlevalue { 
	public Handlevalue(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
