/* Generated by AN DISI Unibo */ 
package it.unibo.coap_server;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractCoap_server extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractCoap_server(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/coap_server/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/coap_server/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitingMessage",waitingMessage);
	    	stateTab.put("messageReceived",messageReceived);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "coap_server tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"coap_server start.\"";
	    	println( temporaryStr );  
	    	//switchTo waitingMessage
	        switchToPlanAsNextState(pr, myselfName, "coap_server_"+myselfName, 
	              "waitingMessage",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitingMessage = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitingMessage",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitingMessage";  
	    	temporaryStr = "\"Waiting message...\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"coap_server_"+myselfName,false,
	          new StateFun[]{stateTab.get("messageReceived") }, 
	          new String[]{"true","M","value" },
	          360000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitingMessage){  
	    	 println( getName() + " plan=waitingMessage WARNING:" + e_waitingMessage.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitingMessage
	    
	    StateFun messageReceived = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("messageReceived",-1);
	    	String myselfName = "messageReceived";  
	    	temporaryStr = "\"Message received. (Distance, Angle):\"";
	    	println( temporaryStr );  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("value(Distance,Angle)");
	    	if( currentMessage != null && currentMessage.msgId().equals("value") && 
	    		pengine.unify(curT, Term.createTerm("value(Discance,Angle)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg = "Distance";
	    		/* Print */
	    		parg =  updateVars( Term.createTerm("value(Discance,Angle)"), 
	    		                    Term.createTerm("value(Distance,Angle)"), 
	    			    		  	Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) println( parg );
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("value(Distance,Angle)");
	    	if( currentMessage != null && currentMessage.msgId().equals("value") && 
	    		pengine.unify(curT, Term.createTerm("value(Discance,Angle)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg = "Angle";
	    		/* Print */
	    		parg =  updateVars( Term.createTerm("value(Discance,Angle)"), 
	    		                    Term.createTerm("value(Distance,Angle)"), 
	    			    		  	Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) println( parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"coap_server_"+myselfName,false,false);
	    }catch(Exception e_messageReceived){  
	    	 println( getName() + " plan=messageReceived WARNING:" + e_messageReceived.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//messageReceived
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
