/* Generated by AN DISI Unibo */ 
package it.unibo.coap_server;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Coap_server extends QActorMsgQueue{
	public MsgHandle_Coap_server(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
