/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.client_simple_actor;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Client_simple_actor extends AbstractClient_simple_actor { 
	public Client_simple_actor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
