/* Generated by AN DISI Unibo */ 
package it.unibo.ctxSystemV0;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxSystemV0  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxsystemv0", "./srcMore/it/unibo/ctxSystemV0/systemv0.pl", 
		"./srcMore/it/unibo/ctxSystemV0/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
