/* Generated by AN DISI Unibo */ 
package it.unibo.coap_client;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Coap_client extends QActorMsgQueue{
	public MsgHandle_Coap_client(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
