/* Generated by AN DISI Unibo */ 
package it.unibo.ctxCoapSystemV0;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxCoapSystemV0  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxcoapsystemv0", "./srcMore/it/unibo/ctxCoapSystemV0/coapsystemv0.pl", 
		"./srcMore/it/unibo/ctxCoapSystemV0/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
