/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.coap_client;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Coap_client extends AbstractCoap_client { 
	public Coap_client(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
