/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.coap_server;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Coap_server extends AbstractCoap_server { 
	public Coap_server(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
