/* Generated by AN DISI Unibo */ 
package it.unibo.server_actor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Server_actor extends QActorMsgQueue{
	public MsgHandle_Server_actor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
