/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.server_actor;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Server_actor extends AbstractServer_actor { 
	public Server_actor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
